language: go
go:
- 1.16.x
env:
  global:
  - GO111MODULE=on
  - secure: YyOgjBU78Q3ZxjCjkctlmmT+RQIsZhcRS0Jym9pTF7RZKC5ke0IcVoWLmLyHI4Tvu28zRvGZRqNTEswr9LZ01NG9sFAsDilnEkX02FMnC8ucrXNtVd7N9m3Rro0AHUROEkXy7Sw2NwZe4iUvPgAobIqEq5QtuUhy8nNLpc7X95qqaG8+ShoeAUOGrq+s1MvSlfMZvAXvMHmSBpnz6GuKpLVQbmPsC8TNAmZuTj9s0yQ31VmFgFesNA/r8ef/Npe7mTUT4nGpIlccELxo32BSad/g3IW1e45i+nQ56cP38FycaCr9oU/slmjz5v41g1STSX8o6EiKSZNJGsX4VVLX2AQdKNEepH5iUJihVzWGImAnNFNaIM+23CMhBcsLj/h42m/zX9FuOPF5dcjAzOmBTpk7ouw/QAogkRXV96PGkZMWfxmQmtjM48jEAE1pwyjskG4ITRhi/FCVvl2g3lE8drenLk78Iq6/OTfAMr4iJn4A3Qn+x+25d5njZBR8aAmLghLgpkYhIsCDgloxailr5tLe1UsNZxRJ2PNZRW/dd2zwT88H7FyoTShlxZOVuXuZ6OJFY75GMWb5FlZ8Kmc4daFUuutQVNnazHGfBRsb5xWKHyiA8Z8gbOBoxd1BJ2lUHICa21V2NYy9SlsyaU+a6WAuAoUmyta6t208OKnyJq0=
  - secure: ZqbaLdAcc6YHkEXoyHAlW6PQIAlxv1n3C0gK5TI8HPxo85LqGdcS/LertKdTrYlppaI+gmj1SH4vmqdvPhIxLZFY8ly19MTrt6LgtW1kLH6osYMJ6SU0EJu7EFj7H09FcSM2zGIrZB2BIcraKFbFzhmWumyWnQejioeNWVcULoeg9GrEC39HOSX8koeDNy6ng3WM74HUI9Y3awnVjr3g8EZWOIA7Io6uAemRVW5Zs4HFolxB11dyn+ivt5IaJRMkIVZKCu5ykA2kF/NbOIYX4nty/0lpVWNM/ISCUOyEy1Q/oAGNKDMUfBsx19bmD4N8MVRxFr01aX3fi7qV1majMUQWm4JKciyBik5IdpYQj2ehgucye8miCXc5DyIQDzINdRkOmTR1vpoCDd3zPrriMtKJzzXnrdPfDtqqEKXEDAqGT4yz2mpvScHZzJg8W/6ADC8CDQ9mVQHPxRTA8zqAN2OBclhzGEFRcG0Fq4YKOAtbhxM8lzBPMR1pbtqbO+GOT8nD3bpD/0YwAVY8poY34PGQ/WAEZChF0XQi83NmqpLUMRZHKVfzcV42jit5fqqiiGCyQZFLJ8Y2CR3tiobqiaD4s1I6bw6f0UsY16GFTqb3GeyEMsaqI1Pcu4EnsmNnqUyoOdwXefcHa/z36ins4X5PtLl6aAMgTiz6wlxFvLI=
  - secure: P5Z9AteX+QPxirj4XGbTt9zOgENevx6s+aDKcCpQDQm7qx28tnp4YTlbeLCSupwxpwg/IcaUk9mz2MWbquMnt8IQM1KlDN7YZsTfkIG553puDBsW3lMLx85whTliihbdRSklj9tRIoLgthQrtcc+9hv48oCbDVYNU3hiN4bMFa+RthYON9UDnSYMNN9U4fm/XUNQHYctwLCVRChDd33r6q8MN9Kt9TkjHagqWqmx7DaqMJn6aWUqD5OT08AV/ZuigA/A5IK94ho8jaHOAHnPKO2Y/vTU4KLI1pJdpmNtgt4b0VNlRFoQ+c36Eo1crQqu998N/fnbfFzXHPR8M0lNpuhoiwmjwNEvKHZSwQjxpyu8Z0mviMmmYzlGOXc5Q1a+jjoOHvNBY3vRnb8mB8r9NPKQgbG30nVKbXBAHRJn/VShjibRBFIK8c08g/U7sNHggkPW4/esMcPL+gAB1JqzsPKs+U2b1UAuqiIRtw+vWTBjcbR5HbmNdz+hlM6wfyLmirzaVshIU/vHOSbp+YpaIQpoIDZqM+6bm63FMXz7nnLxQtf0WLpBZlN2m/JZ5jqxCxuBMt7EqxyeCmxovrnWpYOua5sKnkDjI/YLa4Kb76k6An28dWH12HNh2URnpPxSYyTWzYr/IAIu4QL63R+EChAMmocg7AyKxnbObAcC2S0=
jobs:
  include:
  - stage: build
    install: []
    script:
    - set -e
    - scripts/ci scripts/build
    - scripts/ci scripts/test
    before_deploy: scripts/ci scripts/dist-all
    deploy:
      on:
        tags: true
      skip_cleanup: true
      file_glob: true
      provider: releases
      api_key:
        secure: QEChpHeRG89iU6Ig2SELNjptQkriM8zyOn5aX6+pNbfufMhxp5KR6PihCkbzE/Wx/k8PFM4+AZqiyXO6y16DWaJCKoQKlDKEst3yirEZ78/ajV2zD9kPR5d9nEVUst9Aeuhg2i8LIKsRl+5WOa3q0/3tYn37Flm5AoR86bDqcfSHCkc18OY8fY0HfL8JQNWPDrx/+pbqvUVh4nBo4Tvhp0Y5j+bn2wseb1u7c1m03iKy33qK8JRSn76kv0f8xzLRBBb4eoBR5CyN4jpha/76TJ0imQx1WjJYb2UYL9IwScMsr+la3VJo/OzTKUZRtsi6a77+kzD/nkQBcjhKVvbNil/Qjz0zMLUd2ltFn7kDOTWqIbfQjdzk4Yu+RTRK0KKNgZOxAZ8F3SblUbgUeoN7tI0IkCig7TRNgVzPWjYN6MN+m6PQkF7pHJoxjgnMFDg4wZbUh45HiR/YJ00uw0pLcSWg/aoSg4xbPn3tl8x/PAf1gPDalP0A6f1bCOGAh7YXDZOaBN6uYq9o88tAOiOCeKd781Hcz1tu9/EI70nbEqyZi4xfIdimfh/svSd27LlJtVsn437UDuls41MNjf/FTgyL4RGxIUPPsoX+8gXyU3cWDJOq20bxERvWVaeRgSmKNJ1C8wV+jjJ/KewnW8NwBt0eyM+ygoGwWhPKDiYWexk=
      file: bin/*
    after_deploy: scripts/ci scripts/run-workflow
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    template:
    - "<%{compare_url}|%{commit_subject}> | %{author}"
    - "%{repository_slug} %{branch} | <%{build_url}|#%{build_number}> %{result} in
      %{elapsed_time}"
    rooms:
    - secure: zu/MZURvDivl7qapoRAcOtF6yH9zUwr1YqpDObAlF9mAO0z5VllKVVdDZJZ6QwGNzfl5m4MBXLh7PzXex3VXwbXlGYvUbsvUj9cLo2cLqJqtgBQ4DuVVCJXF4Rj/8sNRx4JfquKGE/Yae07MUXdcIJ1FuOoVHpUTNW1eA0SE5LIWRB8WJiBC53jl5itkUOUqh5l43W+8djpDbcds+vyjE9omwuHW2Zxh7TGqXBSCf2LPmjAzL4eZD2yTE8VUNNbKwx6dBGqpS0Y3Ke4R4bvj9PAZUAqG3dxMKUKU0OyJHg/Jkg5ZqVEoghCSZNGpD2aEfB7C5+hWF1A6Ftvs09qd3cGyioSD88Hj7F7hCzgz2Z+rBMmhvXb9cEeX3iDBDMQ+xd7bDL8bmYMSTVFnnqqz+4SewRCo3efbEF9xaBkUfIpal1Ax0XL9PnBHCniKqVkL99v9ERE5maUoD8W/7JwamqG+ija7P2kblNNLB6G+mh75KHmKU5GNB2+QcLtk3WUtxKLP9KqCUc7CZ9pk02nQlkXClG2nbAWo0QyYq1opbjDMmCpLK1FZiPJpL82QleXfw2JuKIVuUfq9bihOwc1AJvJhJDtNTDQMp+j+2kHBwQOy/EXd1HkK4JTt84+JXzurK3UhcH39g03TCvTpDq/dHy69a706OK4CW2kxIyIfO08=
